name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: ls
      - name: Satellite file upload
        uses: IBM/satellite-config-upload-action@v1.0.1
        with:
          apikey: ${{ secrets.MY_NAME }}
          filename: 'test-job.yml'
          channelUuid: ${{ secrets.MY_AGE }}
          versionName: 'version-12356789'

